version: "2"

run:
  timeout: 5m

linters:
  # defaults: errcheck, govet, ineffassign, staticcheck, unused
  enable:
    - misspell
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports

settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
