version: 2

project_name: sr

before:
  hooks:
    - go mod tidy
    - go test -short ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: klp2
      name: homebrew-sr
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/klp2/sr"
    description: "Bulk reverse DNS (PTR) lookups on CIDR ranges"
    license: "MIT"
    test: |
      assert_match "sr (ShowReverse)", shell_output("#{bin}/sr --help")

release:
  github:
    owner: klp2
    name: sr
